"use client";

import createCache from "@emotion/cache";
import { CacheProvider } from "@emotion/react";
import styled from "@emotion/styled";

import { Inter } from "next/font/google";

import Header from "~/components/Layout/Header";
import Nav from "~/components/Layout/Nav";
import "~/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });
const cache = createCache({ key: "erp" });

// export const metadata: Metadata = {
//   title: "ERP",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CacheProvider value={cache}>
      <html lang="pt-br">
        <Body
          className={inter.className}
          // className={twMerge(
          //   ,
          //   "bg-[#fff] dark:text-white overflow-y-hidden"
          // )}
        >
          <Header />
          <Aside /*className="sticky bottom-0 bg-white dark:bg-[#383e47] float-left h-[calc(100vh-80px)] w-[15vw] py-4 border-r border-[rgb(227, 232, 237)] dark:border-[rgba(17,20,24,.4)]"*/
          >
            <Nav />
          </Aside>
          <Main /*className="bg-white dark:bg-[#252a31] flex justify-center flex-col items-center h-[calc(100vh-80px)] overflow-y-auto"*/
          >
            {children}
          </Main>
        </Body>
      </html>
    </CacheProvider>
  );
}

const Body = styled.body`
  overflow-y: hidden;
  background-color: #fff;

  .dark {
    color: #fff;
  }
`;

const Aside = styled.aside`
  position: sticky;
  bottom: 0;
  background-color: #fff;
  float: left;
  height: calc(100vh - 80px);
  width: 15vw;
  padding-top: 1rem;
  padding-bottom: 1rem;
  border-right: solid 1px rgb(227, 232, 237);
`;

const Main = styled.main`
  background-color: #fff;
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
  height: calc(100vh - 80px);
  overflow-y: auto;
`;
