// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/patrickribeirodev",
        "contact": {
            "name": "Patrick Ribeiro",
            "url": "https://patrickribeiro.dev",
            "email": "contato@patrickribeiro.dev"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pages/{pageID}/components/{componentID}": {
            "patch": {
                "description": "Atualiza parcialmente um componente de uma página",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "components"
                ],
                "summary": "Edita um componente existente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da página",
                        "name": "pageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do componente",
                        "name": "componentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Componente atualizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Content Service API",
	Description:      "Serviço responsável por gerenciar conteúdos e componentes de páginas dentro do CMS.\nFaz parte da arquitetura de microserviços utilizada no portfólio de Patrick Ribeiro.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
