// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/openlab-software/erp",
        "contact": {
            "name": "Patrick Ribeiro",
            "url": "https://patrick.dev.br",
            "email": "contato@patrick.dev.br"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/stocks": {
            "get": {
                "description": "Retorna uma lista de todos os estoques cadastrados.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Lista todos os estoques",
                "responses": {
                    "200": {
                        "description": "Lista de estoques",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infra_rest.stockDTO"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um novo estoque com base no payload fornecido.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Cria um novo estoque",
                "parameters": [
                    {
                        "description": "Payload para criação do estoque",
                        "name": "stock",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infra_rest.createStockDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Estoque criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_rest.stockDTO"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Erro de validação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_infra_rest.createStockDTO": {
            "type": "object",
            "required": [
                "description"
            ],
            "properties": {
                "description": {
                    "description": "Descrição do estoque.",
                    "type": "string",
                    "example": "Estoque Central"
                }
            }
        },
        "internal_infra_rest.stockDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "Descrição do estoque.",
                    "type": "string",
                    "example": "Estoque Central"
                },
                "modified_at": {
                    "type": "string"
                },
                "stock_id": {
                    "description": "ID público do estoque.",
                    "type": "string",
                    "example": "stock_abc123def456"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Stock Service API",
	Description:      "Serviço responsável por gerenciar estoques dentro do ERP.\nFaz parte da arquitetura de microserviços utilizada no portfólio de Patrick Ribeiro.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
