FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata && \
    addgroup -S app && adduser -S app -G app

WORKDIR /app
COPY apps/stock-service/bin/api* .
RUN mv api.exe api 2>/dev/null || true

USER app
EXPOSE 8081
ENTRYPOINT ["./api"]
