FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata && \
    addgroup -S app && adduser -S app -G app

WORKDIR /app
COPY apps/catalog-service/bin/relay* .

USER app
ENTRYPOINT ["./relay"]
