FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata && \
    addgroup -S app && adduser -S app -G app

WORKDIR /app
COPY apps/stock-service/bin/relay* .
RUN mv relay.exe relay 2>/dev/null || true

USER app
ENTRYPOINT ["./relay"]
