---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.20.2.2
    app.quarkus.io/vcs-uri: https://github.com/openlab-software/erp.git
    app.quarkus.io/build-timestamp: 2026-10-09 - 02:43:43 +0000
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: erp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: catalog-service
  namespace: erp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: erp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: catalog-service-stork-discovery
  namespace: erp
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: erp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: view-jobs
  namespace: erp
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: erp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: catalog-service-view-jobs
  namespace: erp
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-jobs
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: catalog-service
    namespace: erp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: erp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: catalog-service-stork-discovery
  namespace: erp
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: catalog-service-stork-discovery
subjects:
  - kind: ServiceAccount
    name: catalog-service
    namespace: erp
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.20.2.2
    app.quarkus.io/vcs-uri: https://github.com/openlab-software/erp.git
    app.quarkus.io/build-timestamp: 2026-10-09 - 02:43:43 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: erp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: catalog-service
  namespace: erp
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: erp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.20.2.2
    app.quarkus.io/vcs-uri: https://github.com/openlab-software/erp.git
    app.quarkus.io/build-timestamp: 2026-10-09 - 02:43:43 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: erp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: catalog-service
  namespace: erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-service
      app.kubernetes.io/part-of: erp
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.20.2.2
        app.quarkus.io/vcs-uri: https://github.com/openlab-software/erp.git
        app.quarkus.io/build-timestamp: 2026-10-09 - 02:43:43 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: catalog-service
        app.kubernetes.io/part-of: erp
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_FLYWAY_ACTIVE
              value: "false"
            - name: OTEL_SDK_DISABLED
              value: "false"
            - name: POSTGRES_HOST
              value: postgres
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-gateway-collector.observability.svc.cluster.local:4317
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-password
                  name: erp-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: erp-secrets
            - name: POSTGRES_PORT
              value: "5432"
          image: ghcr.io/openlab-software/catalog-service:v1.0.7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: catalog-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      initContainers:
        - args:
            - job
            - catalog-service-flyway-init
          image: groundnuty/k8s-wait-for:no-root-v1.7
          imagePullPolicy: Always
          name: wait-for-flyway
      serviceAccountName: catalog-service
---
apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-service-flyway-init
  namespace: erp
spec:
  completionMode: NonIndexed
  template:
    metadata: {}
    spec:
      containers:
        - env:
            - name: OTEL_SDK_DISABLED
              value: "false"
            - name: POSTGRES_HOST
              value: postgres
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-gateway-collector.observability.svc.cluster.local:4317
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-password
                  name: erp-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: erp-secrets
            - name: POSTGRES_PORT
              value: "5432"
            - name: QUARKUS_FLYWAY_ACTIVE
              value: "true"
            - name: QUARKUS_INIT_AND_EXIT
              value: "true"
          image: ghcr.io/openlab-software/catalog-service:v1.0.7
          name: catalog-service-flyway-init
      restartPolicy: OnFailure
      serviceAccountName: catalog-service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.20.2.2
    app.quarkus.io/vcs-uri: https://github.com/openlab-software/erp.git
    app.quarkus.io/build-timestamp: 2026-10-09 - 02:43:43 +0000
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: erp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: catalog-service
  namespace: erp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-service
      app.kubernetes.io/part-of: erp
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  endpoints:
    - scheme: http
      targetPort: 8080
      path: /q/metrics
      interval: 10s
      honorLabels: true
