// stock-service serializes snake_case; the BFF passes it through untouched.
export interface StockItem {
  stock_id: string;
  product_id: string;
  min_value: number | null;
  current_value: number;
  max_value: number | null;
  reserved_value: number;
  available_value: number;
  active: boolean;
}

/** TRANSFER_IN / TRANSFER_OUT are generated by reassignments, never sent by the client. */
export type MovementType =
  | "ENTRY"
  | "EXIT"
  | "ADJUSTMENT"
  | "TRANSFER_IN"
  | "TRANSFER_OUT";

export interface StockMovement {
  movement_id: string;
  stock_id: string;
  product_id: string;
  type: MovementType;
  quantity: number;
  resulting_balance: number;
  reason_id: string | null;
  reference: string | null;
  created_at: string;
}

export interface StockCount {
  count_id: string;
  stock_id: string;
  product_id: string;
  system_value: number;
  counted_value: number;
  created_at: string;
}

export interface ProductBalance {
  product_id: string;
  total_current_value: number;
  total_reserved_value: number;
  total_available_value: number;
  by_stock: {
    stock_id: string;
    current_value: number;
    reserved_value: number;
    available_value: number;
  }[];
}

export interface Reassignment {
  reassignment_id: string;
  from_stock_id: string;
  to_stock_id: string;
  items: { product_id: string; quantity: number; created_at: string }[];
  created_at: string;
}
