// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/openlab-software/erp",
        "contact": {
            "name": "Patrick Ribeiro",
            "url": "https://patrick.dev.br",
            "email": "contato@patrick.dev.br"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories": {
            "get": {
                "description": "Retorna uma lista de categorias. Permite filtrar por uma string de busca 'q'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "List categories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Termo de busca para filtrar categorias pela descrição",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de categorias",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infra_rest.categoryDTO"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma nova categoria com base na descrição fornecida.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Cria uma nova categoria",
                "parameters": [
                    {
                        "description": "Payload para criação da categoria",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infra_rest.createCategoryDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Categoria criada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_rest.categoryDTO"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida (JSON mal formatado)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Erro de validação (ex: descrição em falta)",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "get": {
                "description": "Retorna os detalhes de uma categoria específica.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Busca uma categoria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da Categoria",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalhes da categoria",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_rest.categoryDTO"
                        }
                    },
                    "400": {
                        "description": "ID da categoria inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Categoria não encontrada",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove uma categoria específica do sistema pelo ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Deleta uma categoria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da Categoria",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Categoria deletada com sucesso (sem conteúdo)"
                    },
                    "400": {
                        "description": "ID da categoria inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Categoria não encontrada",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Retorna uma lista de produtos, opcionalmente filtrada por uma query de pesquisa 'q'.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Lista todos os produtos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Query de pesquisa (ex: descrição, id curto)",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de produtos",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_infra_rest.productDTO"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um novo produto no catálogo com base no payload fornecido.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Cria um novo produto",
                "parameters": [
                    {
                        "description": "Payload para criação do produto",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infra_rest.createProductDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Produto criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_rest.productDTO"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "description": "Retorna um único produto dado seu ID público.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Obtém um produto pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID público do produto (formato prod_...)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Produto encontrado",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_rest.productDTO"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta um produto permanentemente usando seu ID público.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Deleta um produto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID público do produto (formato prod_...)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_infra_rest.categoryDTO": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "O ID único da categoria.",
                    "type": "string",
                    "example": "cat_2a1b3c4d5e"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "A descrição da categoria.",
                    "type": "string",
                    "example": "Eletrônicos"
                },
                "modified_at": {
                    "type": "string"
                }
            }
        },
        "internal_infra_rest.categoryInProductDTO": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "ID público da categoria.",
                    "type": "string",
                    "example": "cat_2a1b3c4d5e"
                },
                "description": {
                    "description": "Descrição da categoria.",
                    "type": "string",
                    "example": "Eletrônicos"
                }
            }
        },
        "internal_infra_rest.createCategoryDTO": {
            "type": "object",
            "required": [
                "description"
            ],
            "properties": {
                "description": {
                    "description": "A descrição da categoria.",
                    "type": "string",
                    "example": "Eletrônicos"
                }
            }
        },
        "internal_infra_rest.createProductDTO": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "ID público da Categoria à qual o produto pertence.",
                    "type": "string",
                    "example": "cat_abc123def456"
                },
                "description": {
                    "description": "Descrição completa do produto.",
                    "type": "string",
                    "example": "Smartphone X Pro 256GB"
                },
                "short_description": {
                    "description": "Descrição curta do produto.",
                    "type": "string",
                    "example": "Smartphone X Pro"
                },
                "unit_of_measure": {
                    "description": "Unidade de medida (ex: UN, KG, MT).",
                    "type": "string",
                    "example": "UN"
                }
            }
        },
        "internal_infra_rest.productDTO": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Categoria associada ao produto.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_infra_rest.categoryInProductDTO"
                        }
                    ]
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "Descrição completa do produto.",
                    "type": "string",
                    "example": "Smartphone X Pro 256GB"
                },
                "modified_at": {
                    "type": "string"
                },
                "product_id": {
                    "description": "ID público do produto.",
                    "type": "string",
                    "example": "prod_xyz789uvw012"
                },
                "short_description": {
                    "description": "Descrição curta do produto.",
                    "type": "string",
                    "example": "Smartphone X Pro"
                },
                "status": {
                    "description": "Status do produto (ACTIVE, INACTIVE).",
                    "type": "string",
                    "example": "INACTIVE"
                },
                "unit_of_measure": {
                    "description": "Unidade de medida (ex: UN, KG, MT).",
                    "type": "string",
                    "example": "UN"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/catalog-service/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Catalog Service API",
	Description:      "Serviço responsável por gerenciar o catálogo de produtos dentro do ERP.\nFaz parte da arquitetura de microserviços utilizada no portfólio de Patrick Ribeiro.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
